---
title: "Model Validation Assignment"
author: "Glenn Barber"
date: "2023-06-05"
output: word_document
---

```{r}
library(tidyverse)
library(lubridate)
library(tidymodels)
library(esquisse)
```

```{r}
bike <- read_csv("bike_cleaned.csv")
```

```{r}
bike = bike %>% mutate(dteday = mdy(dteday))
#Note that mdy is a lubridate package function
#You can read more about lubridate here: https://lubridate.tidyverse.org/
```

```{r}
bike = bike %>% mutate_if(is.character, as_factor)
bike = bike %>% mutate(hr = as_factor(hr))
```

```{r}
set.seed(1234)
bike_split = initial_split(bike, prop = 0.70, strata = count)
train = training(bike_split)
test = testing(bike_split)
```

```{r}
train2 = train %>% dplyr::select("season", "mnth", "hr", "holiday", "weekday", "temp", "weathersit")
```

```{r}
bike_recipe = recipe(count ~ season + mnth + hr + holiday + weekday + temp + weathersit , train)

lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm") #specify the specify type of linear tool we want to use 

lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike_recipe)

lm_fit = fit(lm_wflow, train)
```

```{r}
summary(lm_fit$fit$fit$fit)
```

```{r}
lm_fit %>% predict(test) %>% bind_cols(test) %>% metrics(truth = count, estimate = .pred)

```

```{r}
pred_test <- predict(lm_fit,test) %>% bind_cols(test) %>% metrics(truth = count, estimate = .pred)


```

